### ISSUE TITLE
No such operator image::read_file

### ISSUE THREAD

**Issue by WDK502** [sithu31296/semantic-segmentation#10]
When i'm running camvid.py, This happened "No such operator image::read_file"， 
Excuse me, why is this?
**Related error messages：**
Traceback (most recent call last):
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-66bfffc647ab>", line 1, in <module>
    runfile('D:/PYcode/Code6/datasets/camvid.py', wdir='D:/PYcode/Code6/datasets')
  File "D:\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PYcode/Code6/datasets/camvid.py", line 86, in <module>
    image, label = next(iter(dataloader))
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:/PYcode/Code6/datasets/camvid.py", line 54, in __getitem__
    image = io.image.read_file(img_path)
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torchvision\io\image.py", line 79, in read_file
    data = torch.ops.image.read_file(path)
  File "D:\anaconda3\envs\TF2.5\lib\site-packages\torch\_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file

**Comment by sithu31296** [comment]
I think your pytorch is very low. To run the code, you need to have torch >= 1.8.1 and torchvision >= 0.9.1.

**Comment by WDK502** [comment]
thanks for your answer!
