### ISSUE TITLE
Why is '-1' for parameter IGNORE_LABEL in ade20k.yaml?

### ISSUE THREAD

**Issue by star4s** [sithu31296/semantic-segmentation#24]
Why is '-1' for parameter IGNORE_LABEL in ade20k.yaml?

When I train  for ade20k.yaml, I have some error.

python tools/train.py --cfg configs/ade20k.yaml &

-->
Found 20210 training images.
Found 2000 validation images.

Epoch: [1/10] Iter: [3/10105] LR: 0.00010003 Loss: 6.46664333:   0%|                                                                                                                                       | 3/10105 [00:02<2:19:10,  1.21it/s]
Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(cfg, gpu, save_dir)
  File "tools/train.py", line 69, in main
    for iter, (img, lbl) in pbar:
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File /.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File /.conda/envs/Lawin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/semantic-segmentation/semseg/datasets/ade20k.py", line 73, in __getitem__
    image, label = self.transform(image, label)
  File /semantic-segmentation/semseg/augmentations.py", line 20, in __call__
    img, mask = transform(img, mask)
  File /semantic-segmentation/semseg/augmentations.py", line 329, in __call__
    mask = TF.pad(mask, padding, fill=self.seg_fill)
  File "/.conda/envs/Lawin/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 474, in pad
    return F_t.pad(img, padding=padding, fill=fill, padding_mode=padding_mode)
  File /.conda/envs/Lawin/lib/python3.6/site-packages/torchvision/transforms/functional_tensor.py", line 475, in pad
    img = torch_pad(img, p, mode=padding_mode, value=float(fill))
  File /.conda/envs/Lawin/lib/python3.6/site-packages/torch/nn/functional.py", line 4174, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: value cannot be converted to type uint8_t without overflow: -1

**Comment by sithu31296** [comment]
Sorry for late reply. `-1` represents the background class (ignore in loss calculation) in ADE (other repo use 255). You can also use 255 but you have to modify it yourself.
